version: "3.9"
networks:
  net:
    driver: bridge
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./src/docker/postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - net
